version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "GeneralCacheLambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hess4fhdx117"
s3_prefix = "GeneralCacheLambda"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
